@startuml

class Jugador {
- Dictionary<String recurso, Int cantidad> recursos
+ agregarRecurso(String recurso, int cantidad)
}

abstract class Construccion{
- Int puntosDeVictoria
- Producir producir
- Jugador dueño

+ producirRecurso(String recurso)
}

class Poblado{
    + construir(jugador : Jugador) : Construccion
}

class Ciudad{
    + construir(jugador : Jugador) : Construccion
}

class Carretera{
    + construir(jugador : Jugador) : Construccion
}

interface Producir{
+ producir(String recurso, Jugador dueño)
}

class ProducirX1{
producir(String recurso, Jugador dueño)
}

class ProducirX2{
producir(String recurso, Jugador dueño)
}
class NoProducir{
producir(String recurso, Jugador dueño)
}

Jugador "1" *-- "*" Construccion

Construccion <|-- Poblado
Construccion <|-- Ciudad
Construccion <|-- Carretera

Construccion "1" *-- "1" Producir

Producir <|.. ProducirX1
Producir <|.. ProducirX2
Producir <|.. NoProducir
@enduml